### ISSUE TITLE
Project is almost inreproducible. - 10

### ISSUE THREAD

**Issue by dliviya** [DSCI-310/DSCI-310-Group-2#61]

**Comment by eahn01** [comment]
1. diagnosis and attribute_box_plots merge issue: 
> https://github.com/DSCI-310/DSCI-310-Group-2/commit/0ee1697aa5ebbb0065ca2f9e08a6cf7637fe0631
> https://github.com/DSCI-310/DSCI-310-Group-2/commit/c1d06bb1893df2f31b021d3cf555b3d2aec83f7f

2. no repository inside the container the docker command is probably lacking a -v argument
> https://github.com/DSCI-310/DSCI-310-Group-2/commit/b726e9cebf45eb981218ad455a23ee205f2e9aa9

3. There is no copy-paste instruction for cloning the repository.
> https://github.com/DSCI-310/DSCI-310-Group-2/commit/443f99f49c016f4bf3c373eda50909c3e0afc734

4. Problems in running the analysis due to code like source("../R/attribe_box_plots.r")
> replaced with
> https://github.com/DSCI-310/DSCI-310-Group-2/commit/d3f4edc4f2de1df312107ae115185bb9c375a822
